services:

  migration:
    image: ${CI_REGISTRY_IMAGE}/api:${CI_COMMIT_SHORT_SHA}
    deploy:
      replicas: 1
      restart_policy:
        condition: none
      labels:
        - traefik.enable=false
    command: ["alembic", "upgrade", "head"]
    secrets:
      - ALL_TXT_BACKEND_MIGRATION

  api:
    image: ${CI_REGISTRY_IMAGE}/api:${CI_COMMIT_SHORT_SHA}
    deploy:
      replicas: 1
      labels:
        - traefik.enable=true 
        - traefik.http.services.all_txt_api.loadbalancer.server.port=8000 
        - traefik.http.routers.all_txt_api.rule=Host(`api.all-txt.de`)
        - traefik.http.routers.all_txt_api.entrypoints=websecure
        - traefik.http.routers.all_txt_api.tls=true
        - traefik.http.routers.all_txt_api.tls.certresolver=myresolver
    networks:
      - traefik_public
    command: ["gunicorn", "api:app", "--workers=2", "--worker-class=uvicorn.workers.UvicornWorker", "--bind=0.0.0.0:8000", "--access-logfile", "-"]
    environment:
      - ALL_TXT_BACKEND_CORS__ALLOW_ORIGINS=["https://box.all-txt.de"]
    secrets:
      - ALL_TXT_BACKEND_DATABASE
      - ALL_TXT_BACKEND_REDIS

  redis:
    image: redis:7
    deploy:
      replicas: 1
    command: ["redis-server", "--requirepass ${REDIS_PASSWORD}"]
    networks:
      - traefik_public

  webapp:
    image: ${CI_REGISTRY_IMAGE}/webapp:${CI_COMMIT_SHORT_SHA}
    deploy:
      replicas: 1
      labels:
        - traefik.enable=true 
        - traefik.http.services.all_txt_webapp.loadbalancer.server.port=80 
        - traefik.http.routers.all_txt_webapp.rule=Host(`box.all-txt.de`)
        - traefik.http.routers.all_txt_webapp.entrypoints=websecure
        - traefik.http.routers.all_txt_webapp.tls=true
        - traefik.http.routers.all_txt_webapp.tls.certresolver=myresolver
    networks:
      - traefik_public
    command: ["nginx", "-g", "daemon off;"]


secrets:
  ALL_TXT_BACKEND_DATABASE:
    file: /tmp/ALL_TXT_BACKEND_DATABASE
  ALL_TXT_BACKEND_MIGRATION:
    file: /tmp/ALL_TXT_BACKEND_MIGRATION
  ALL_TXT_BACKEND_REDIS:
    file: /tmp/ALL_TXT_BACKEND_REDIS
  
networks:
  traefik_public:
    external: true