// This file is auto-generated by @hey-api/openapi-ts

export const $HTTPValidationError = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const $PipelineResponse = {
    properties: {
        original_text: {
            type: 'string',
            title: 'Original Text'
        },
        suggestions: {
            items: {
                '$ref': '#/components/schemas/SuggestionTarget'
            },
            type: 'array',
            title: 'Suggestions'
        }
    },
    type: 'object',
    required: ['original_text', 'suggestions'],
    title: 'PipelineResponse'
} as const;

export const $Suggestion = {
    properties: {
        variant: {
            type: 'string',
            title: 'Variant'
        },
        text: {
            type: 'string',
            title: 'Text'
        }
    },
    type: 'object',
    required: ['variant', 'text'],
    title: 'Suggestion'
} as const;

export const $SuggestionTarget = {
    properties: {
        id: {
            type: 'string',
            title: 'Id'
        },
        type: {
            type: 'string',
            enum: ['gender'],
            const: 'gender',
            title: 'Type'
        },
        comment: {
            type: 'string',
            title: 'Comment'
        },
        original: {
            type: 'string',
            title: 'Original'
        },
        suggestions: {
            items: {
                '$ref': '#/components/schemas/Suggestion'
            },
            type: 'array',
            title: 'Suggestions'
        },
        start: {
            type: 'integer',
            title: 'Start'
        },
        stop: {
            type: 'integer',
            title: 'Stop'
        }
    },
    type: 'object',
    required: ['id', 'type', 'comment', 'original', 'suggestions', 'start', 'stop'],
    title: 'SuggestionTarget'
} as const;

export const $TextInput = {
    properties: {
        text: {
            type: 'string',
            title: 'Text'
        }
    },
    type: 'object',
    required: ['text'],
    title: 'TextInput'
} as const;

export const $ValidationError = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;