// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import type { BaseHttpRequest } from './core/BaseHttpRequest';
import type { RunData, RunResponse } from './types.gen';

export class PipelineService {
    constructor(public readonly httpRequest: BaseHttpRequest) { }
    
    /**
     * Run
     * @param data The data for the request.
     * @param data.requestBody
     * @returns PipelineResponse Successful Response
     * @throws ApiError
     */
    public run(data: RunData): CancelablePromise<RunResponse> {
        return this.httpRequest.request({
            method: 'POST',
            url: '/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
}