// This file is auto-generated by @hey-api/openapi-ts

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type PipelineResponse = {
    original_text: string;
    suggestions: Array<SuggestionTarget>;
};

export type Suggestion = {
    variant: string;
    text: string;
};

export type SuggestionTarget = {
    id: string;
    type: 'gender';
    comment: string;
    original: string;
    suggestions: Array<Suggestion>;
    start: number;
    stop: number;
};

export type type = 'gender';

export type TextInput = {
    text: string;
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type RunData = {
    requestBody: TextInput;
};

export type RunResponse = PipelineResponse;

export type $OpenApiTs = {
    '/': {
        post: {
            req: RunData;
            res: {
                /**
                 * Successful Response
                 */
                200: PipelineResponse;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
};